apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: da774m2sz-python 
  janus-idp.io/tekton: da774m2sz-python
  backstage.io/kubernetes-id: da774m2sz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: da774m2sz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml